# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nafrin <shazeen2405@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/06/05 12:02:01 by nafrin            #+#    #+#              #
#    Updated: 2022/06/05 12:02:05 by nafrin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# NAME = rush-02
# SRC = *.c
# FLAGS = -Wall -Wextra -Werror
# all : $(NAME)
# RM = /bin/rm -f
# $(NAME) : 
# 	gcc  $(FLAGS) -o $(NAME) $(SRC)
# clean : 
# 	$(RM) *.o
# fclean : clean 
# 		$(RM) $(NAME)


all:
	gcc -Wall -Wextra -Werror -o rush-02 *.c
fclean:
	rm *.o rush-02